#include <iostream>
#include <queue>
using namespace std;
void firstNonRepeating(string str) {
    queue<char> q;
    int freq[26] = {0};
    for (char ch : str) {
        q.push(ch);
        freq[ch - 'a']++;
        while (!q.empty() && freq[q.front() - 'a'] > 1) {
            q.pop();
        }
        if (q.empty())
            cout << -1 << " ";
        else
            cout << q.front() << " ";
    }
    cout << endl;
}

int main() {
    string input = "aabc"; 
    firstNonRepeating(input);
    return 0;
}